baseURL: 'https://green-river-047e6a503.1.azurestaticapps.net/'
title: Azure Cologne Meetup
author: 
  name: "Elio Struyf"
copyright: 'Copyright © 2022, Elio Struyf; all rights reserved.'
paginate: 3
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: true
theme: beautifulhugo

ignoreErrors:
  - error-remote-getjson

params:
  since: 2022

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10

taxonomies:
  category: categories
  tag: tags
  series: series

privacy:
  vimeo:
    disabled: false
    simple: true
  twitter:
    disabled: false
    enableDNT: true
    simple: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
